#!/bin/bash

error () {
    echo $@ >/dev/stderr
}

die () {
    error $@
    exit 1
}

usage () {
    echo -e "Usage is:\n\t$0 [-mv] <source> <destination>"
}

verbose=false

while getopts 'm:v' val
do
  case $val in
    m) module=${OPTARG} ;;
    v) verbose=true ;;
    ?) exit 1;
  esac
done

let nopts=OPTIND-1
shift ${nopts}


#Sourcing BASEURL
source ~/.docconvertrc

if [ -n "$APIKEY" ]
then
    USER=$(echo $APIKEY|cut -d- -f1)
    APIKEY=$(echo $APIKEY|cut -d- -f2)
    APIKEY=$(echo -n $APIKEY-$(date +%Y-%m-%d) | shasum | cut -d\  -f 1)
    APIKEY="${USER}-${APIKEY}"
fi

if [ -n "$module" ]
then
    echo $BASEURL
    BASEURL=$BASEURL/module/$module
    echo $BASEURL
fi

if [ -z "$2" ]
then
    usage
    exit 1
fi

infile=$1
outfile=$2

if [ ! -r $infile ]
then
    die Cannot open "${infile}"
fi

inmime=$(file -b --mime-type $infile)

insuffix="${infile##*.}"
outsuffix="${outfile##*.}"

tmpfile=$(mktemp)

if $verbose
then
    echo curl -s -D -  -F "file=@${infile};type=${inmime}" -F apikey=${APIKEY} $BASEURL/$outsuffix -o $tmpfile
fi
result=$(curl -s -D -  -F "file=@${infile};type=${inmime}" -F apikey=${APIKEY} $BASEURL/$outsuffix -o $tmpfile | egrep -o '^HTTP/[[:digit:]]\.[[:digit:]] [[:digit:]]{3}' | cut -d' ' -f2 | tail -n 1)

errorState=false

case $result in
    200)
	mv $tmpfile $outfile
	;;
    404)
	echo "No converter available for converting to '$outsuffix'"
	errorState=true
	;;
    415)
	echo "Converting '$insuffix' to '$outsuffix' is not supported"
	errorState=true
	;;
    *)
	echo Unknown error $result
	errorState=true
	;;
esac

if $errorState
then
    echo $tmpfile
    cat $tmpfile
    rm $tmpfile
    exit 1
fi
