#!/bin/bash

. ../../helpers/testSuite

res=$(runcmd list)

testjq "sources exist" "${res}" '.[]|select (. == "sources")'
testjq "targets exist" "${res}" '.[]|select (. == "targets")'
testjq "modules exist" "${res}" '.[]|select (. == "modules")'

