#!/bin/bash

if [ -r ~/.docconvertrc ]
then
  source ~/.docconvertrc
fi

if [ -z "$BASEURL" ]
then
  echo \$BASEURL not set unable to proceed
  exit 1
fi

runcmd () {
  curl -s $BASEURL/$1
}

testjq () {
  echo -n "$1: "
  if echo $2 | jq -e "$3" >/dev/null
  then
    echo pass
  else
    echo fail
  fi
}
